// qlist100000.c

inherit SKILL;
#include <ansi.h>

mapping *quest = ({
	([      "quest":                "护塔僧",
		"quest_type":           "杀",
		"where":		"天龙寺",
		"diff":			2,
	]),
	([      "quest":                "妓女",
		"quest_type":           "杀",
		"where":		"千金楼",
		"diff":			2,
	]),
	([      "quest":                "人贩子",
		"quest_type":           "杀",
		"where":		"千金楼",
		"diff":			2,
	]),
	([      "quest":                "春红",
		"quest_type":           "杀",
		"where":		"千金楼",
		"diff":			2,
	]),
	([      "quest":                "夏红",
		"quest_type":           "杀",
		"where":		"千金楼",
		"diff":			2,
	]),
	([      "quest":                "宋承琳",
		"quest_type":           "杀",
		"where":		"千金楼",
		"diff":			2,
	]),
	([      "quest":                "年青公子",
		"quest_type":           "杀",
		"where":		"千金楼",
		"diff":			2,
	]),
	([      "quest":                HIR"夏红的头颅"NOR,
		"quest_type":           "寻",
		"where":		"千金楼",
		"diff":			2,
	]),
	([      "quest":                HIR"舞女的头颅"NOR,
		"quest_type":           "寻",
		"where":		"千金楼",
		"diff":			2,
	]),
	([      "quest":                HIR"陪酒女郎的头颅"NOR,
		"quest_type":           "寻",
		"where":		"千金楼",
		"diff":			2,
	]),
	([      "quest":                RED"霓红连衣裙"NOR,
		"quest_type":           "寻",
		"where":		"千金楼",
		"diff":			2,
	]),
	([      "quest":                "宋青书",
		"quest_type":           "杀",
		"where":		"武当",
		"diff":			2,
	]),
	([      "quest":                "申人俊",
		"quest_type":           "杀",
		"where":		"青城派",
		"diff":			2,
	]),
	([      "quest":                "吉人通",
		"quest_type":           "杀",
		"where":		"青城派",
		"diff":			2,
	]),
	([      "quest":                "秦宝德",
		"quest_type":           "杀",
		"where":		"桃源棺材店",
		"diff":			2,
	]),
	([      "quest":                "竹器铺老板",
		"quest_type":           "杀",
		"where":		"桃源竹器铺",
		"diff":			2,
	]),
	([      "quest":                "杨老四",
		"quest_type":           "杀",
		"where":		"桃源布庄",
		"diff":			2,
	]),
	([      "quest":                "皇宫卫士",
		"quest_type":           "杀",
		"where":		"皇宫",
		"diff":			2,
	]),
	([      "quest":                "黄衣使者",
		"quest_type":           "杀",
		"where":		"佛山以南的渔港",
		"diff":			2,
	]),
	([      "quest":                "张康",
		"quest_type":           "杀",
		"where":		"佛山以东的林间道",
		"diff":			2,
	]),
	([      "quest":                "张朝唐",
		"quest_type":           "杀",
		"where":		"佛山以南的渔港",
		"diff":			2,
	]),
	([      "quest":                HIR"莎椤花"NOR,
		"quest_type":           "寻",
		"where":		"佛山以东的林间道",
		"diff":			2,
	]),
	([      "quest":                HIB"蕙兰花"NOR,
		"quest_type":           "寻",
		"where":		"佛山以东的林间道",
		"diff":			2,
	]),
	([      "quest":                "亲兵",
		"quest_type":           "杀",
		"where":		"成都提督府",
		"diff":			2,
	]),
});
mapping query_quest()
{
	return quest[random(sizeof(quest))];
}
