// qlist224000.c

inherit SKILL;
#include <ansi.h>

mapping *quest = ({
        ([      "quest":                "耶律齐",
                "quest_type":           "杀",
                "where":                "襄阳城",
                "diff":                 4,
        ]),
        ([      "quest":                "谷虚道长",
                "quest_type":           "杀",
                "where":                "武当派",
                "diff":                 4,
        ]),
        ([      "quest":                "护院",
                "quest_type":           "杀",
                "where":                "大理镇南王府",
                "diff":                 4,
        ]),
        ([      "quest":                "韩宝驹",
                "quest_type":           "杀",
                "where":                "归云庄",
                "diff":                 4,
        ]),
        ([      "quest":                "南希仁",
                "quest_type":           "杀",
                "where":                "归云庄",
                "diff":                 4,
        ]),
        ([      "quest":                "杨成协",
                "quest_type":           "杀",
                "where":                "杭州六合塔",
                "diff":                 4,
        ]),
        ([      "quest":                "龙骏",
                "quest_type":           "杀",
                "where":                "杭州六合塔",
                "diff":                 4,
        ]),
        ([      "quest":                "米为义",
                "quest_type":           "杀",
                "where":                "衡山派",
                "diff":                 4,
        ]),
        ([      "quest":                "田伯光",
                "quest_type":           "杀",
                "where":                "衡山派",
                "diff":                 4,
        ]),
        ([      "quest":                "向大年",
                "quest_type":           "杀",
                "where":                "衡山派",
                "diff":                 4,
        ]),
        ([      "quest":                "叶二娘",
                "quest_type":           "杀",
                "where":                "灵州",
                "diff":                 4,
        ]),
        ([      "quest":                "狄修",
                "quest_type":           "杀",
                "where":                "嵩山派",
                "diff":                 4,
        ]),
        ([      "quest":                "万大平",
                "quest_type":           "杀",
                "where":                "嵩山派",
                "diff":                 4,
        ]),
        ([      "quest":                "丹青生",
                "quest_type":           "杀",
                "where":                "梅庄",
                "diff":                 4,
        ]),
        ([      "quest":                "施令威",
                "quest_type":           "杀",
                "where":                "梅庄",
                "diff":                 4,
        ]),
        ([      "quest":                "黄真",
                "quest_type":           "杀",
                "where":                "梅庄",
                "diff":                 4,
        ]),
        ([      "quest":                "陈有德",
                "quest_type":           "杀",
                "where":                "扬州",
                "diff":                 4,
        ]),
        ([      "quest":                "花铁干",
                "quest_type":           "杀",
                "where":                "血刀门附近",
                "diff":                 4,
        ]),
        ([      "quest":                "顾炎武",
                "quest_type":           "杀",
                "where":                "北京",
                "diff":                 4,
        ]),
        ([      "quest":                "水岱",
                "quest_type":           "杀",
                "where":                "血刀门",
                "diff":                 4,
        ]),
        ([      "quest":                "刘虹瑛",
                "quest_type":           "杀",
                "where":                "金牛武馆",
                "diff":                 4,
        ]),
        ([      "quest":                "龙铨",
                "quest_type":           "杀",
                "where":                "金牛武馆",
                "diff":                 4,
        ]),
        ([      "quest":                "马五德",
                "quest_type":           "杀",
                "where":                "金牛武馆",
                "diff":                 4,
        ]),
        ([      "quest":                "玉萧",
                "quest_type":           "寻",
                "where":                "桃花岛",
                "diff":                 4,
        ]),
        ([      "quest":                "明珠",
                "quest_type":           "寻",
                "where":                "桃花岛",
                "diff":                 4,
        ]),
        ([      "quest":                "拳法总诀",
                "quest_type":           "寻",
                "where":                "桃源书屋",
                "diff":                 4,
        ]),
        ([      "quest":                "棋谱",
                "quest_type":           "寻",
                "where":                "逍遥派",
                "diff":                 4,
        ]),
        ([      "quest":                "玉女剑谱",
                "quest_type":           "寻",
                "where":                "古墓派",
                "diff":                 4,
        ]),
        ([      "quest":                "天山器法",
                "quest_type":           "寻",
                "where":                "星宿派",
                "diff":                 4,
        ]),
        ([      "quest":                "圣火令",
                "quest_type":           "寻",
                "where":                "明教",
                "diff":                 4,
        ]),
        ([      "quest":                "柯镇恶",
                "quest_type":           "杀",
                "where":                "归云庄",
                "diff":                 4,
        ]),
        ([      "quest":                "高彦超",
                "quest_type":           "杀",
                "where":                "归云庄",
                "diff":                 4,
        ]),
});

mapping query_quest()
{
        return quest[random(sizeof(quest))];
}
