// qlist1000.c

#include <ansi.h>
inherit SKILL;

mapping *quest = ({
	([      "quest":                "陪从",
		"quest_type":           "杀",
		"where":                "天山附近",
		"diff":                 1,
	]),
	([      "quest":                "毒蛇",
		"quest_type":           "杀",
		"where":                "扬州郊外的树林里",
		"diff":                 1,
	]),
	([      "quest":                "竹叶青蛇",
		"quest_type":           "杀",
		"where":                "神龙岛",
		"diff":                 1,
	]),
	([      "quest":                "青蛇胆",
		"quest_type":           "寻",
		"where":                "神龙岛",
		"diff":                 1,
	]),
	([      "quest":                "腹蛇胆",
		"quest_type":           "寻",
		"where":                "神龙岛",
		"diff":                 1,
	]),
	([      "quest":                "腹蛇",
		"quest_type":           "杀",
		"where":                "神龙岛",
		"diff":                 1,
	]),
	([      "quest":                "店小二",
		"quest_type":           "杀",
		"where":                "客栈",
		"diff":                 1,
	]),
	([      "quest":                "蜜蜂",
		"quest_type":           "杀",
		"where":                "扬州以西的终南山口",
		"diff":                 1,
	]),
	([      "quest":                "风良",
		"quest_type":           "杀",
		"where":                "扬州东南的小树林",
		"diff":                 1,
	]),
	([      "quest":                "高三娘子",
		"quest_type":           "杀",
		"where":                "扬州东南的小树林",
		"diff":                 1,
	]),
	([      "quest":                "小童",
		"quest_type":           "杀",
		"where":                "桃源西街",
		"diff":                 1,
	]),
	([      "quest":                "收破烂的",
		"quest_type":           "杀",
		"where":                "扬州一带",
		"diff":                 1,
	]),
	([      "quest":                "小鸟",
		"quest_type":           "杀",
		"where":                "桃源城的小树林",
		"diff":                 1,
	]),
	([      "quest":                "野兔",
		"quest_type":           "杀",
		"where":                "桃源城的小树林",
		"diff":                 1,
	]),
	([      "quest":                "松鼠",
		"quest_type":           "杀",
		"where":                "桃源城的小树林",
		"diff":                 1,
	]),
	([      "quest":                "苍蝇",
		"quest_type":           "杀",
		"where":                "桃源城集市肉场",
		"diff":                 1,
	]),
	([      "quest":                "蝴蝶",
		"quest_type":           "杀",
		"where":                "桃源城的大槐树园",
		"diff":                 1,
	]),
	([      "quest":                "盛皮罗客商",
		"quest_type":           "杀",
		"where":                "天山附近",
		"diff":                 1,
	]),
	([      "quest":                "疯狗",
		"quest_type":           "杀",
		"where":                "桃源城的城隍庙里",
		"diff":                 1,
	]),
	([      "quest":                "波斯商人",
		"quest_type":           "杀",
		"where":                "天山附近",
		"diff":                 1,
	]),
	([      "quest":                "桃符纸",
		"quest_type":           "找",
		"where":                "桃源城的棺材店",
		"diff":                 1,
	]),
});

mapping query_quest()
{
	return quest[random(sizeof(quest))];
}
