// qlist1200000.c

inherit SKILL;

mapping *quest = ({
	([      "quest":                "道正禅师",
		"quest_type":           "杀",
		"where":                "少林派",
		"diff":                 4,
	]),
	([      "quest":                "道一禅师",
		"quest_type":           "杀",
		"where":                "少林派",
		"diff":                 4,
	]),
	([      "quest":                "道象禅师",
		"quest_type":           "杀",
		"where":                "少林派",
		"diff":                 4,
	]),
	([      "quest":                "道相禅师",
		"quest_type":           "杀",
		"where":                "少林派",
		"diff":                 4,
	]),
	([      "quest":                "道品禅师",
		"quest_type":           "杀",
		"where":                "少林派",
		"diff":                 4,
	]),
	([      "quest":                "道觉禅师",
		"quest_type":           "杀",
		"where":                "少林派",
		"diff":                 4,
	]),
	([      "quest":                "道果禅师",
		"quest_type":           "杀",
		"where":                "少林派",
		"diff":                 4,
	]),
	([      "quest":                "道成禅师",
		"quest_type":           "杀",
		"where":                "少林派",
		"diff":                 4,
	]),
	([      "quest":                "道尘禅师",
		"quest_type":           "杀",
		"where":                "少林派",
		"diff":                 4,
	]),
	([      "quest":                "范遥",
		"quest_type":           "杀",
		"where":                "明教",
		"diff":                 4,
	]),
	([      "quest":                "梅剑",
		"quest_type":           "杀",
		"where":                "灵鹫宫",
		"diff":                 4,
	]),
	([      "quest":                "何不净",
		"quest_type":           "杀",
		"where":                "丐帮",
		"diff":                 4,
	]),
	([      "quest":                "江上游",
		"quest_type":           "杀",
		"where":                "丐帮",
		"diff":                 4,
	]),
	([      "quest":                "快活三",
		"quest_type":           "杀",
		"where":                "丐帮",
		"diff":                 4,
	]),
	([      "quest":                "李斧头",
		"quest_type":           "杀",
		"where":                "丐帮",
		"diff":                 4,
	]),
	([      "quest":                "黎生",
		"quest_type":           "杀",
		"where":                "丐帮",
		"diff":                 4,
	]),
	([      "quest":                "马俱为",
		"quest_type":           "杀",
		"where":                "丐帮",
		"diff":                 4,
	]),
	([      "quest":                "莫不收",
		"quest_type":           "杀",
		"where":                "丐帮",
		"diff":                 4,
	]),
	([      "quest":                "裘万家",
		"quest_type":           "杀",
		"where":                "丐帮",
		"diff":                 4,
	]),
	([      "quest":                "全冠清",
		"quest_type":           "杀",
		"where":                "丐帮",
		"diff":                 4,
	]),
	([      "quest":                "余洪兴",
		"quest_type":           "杀",
		"where":                "丐帮",
		"diff":                 4,
	]),
	([      "quest":                "赵狗儿",
		"quest_type":           "杀",
		"where":                "丐帮",
		"diff":                 4,
	]),
	([      "quest":                "贝锦仪",
		"quest_type":           "杀",
		"where":                "峨嵋派",
		"diff":                 4,
	]),
	([      "quest":                "方碧琳",
		"quest_type":           "杀",
		"pot_bonus":            20,
		"where":                "峨嵋派",
		"diff":                 4,
	]),
	([      "quest":                "纪晓芙",
		"quest_type":           "杀",
		"where":                "峨嵋派",
		"diff":                 4,
	]),
	([      "quest":                "李明霞",
		"quest_type":           "杀",
		"where":                "峨嵋派",
		"diff":                 4,
	]),
	([      "quest":                "赵灵珠",
		"quest_type":           "杀",
		"where":                "峨嵋派",
		"diff":                 4,
	]),
	([      "quest":                "苏梦清",
		"quest_type":           "杀",
		"where":                "峨嵋派",
		"diff":                 4,
	]),

});

mapping query_quest()
{
	return quest[random(sizeof(quest))];
}
