// qlist100000.c

inherit SKILL;
#include <ansi.h>

mapping *quest = ({
	([      "quest":                HIM"紫袍"NOR,
		"quest_type":           "寻",
		"where":		"桃源考场",
		"diff":			2,
	]),
	([      "quest":                "陈七",
		"quest_type":           "杀",
		"where":		"福威镖局",
		"diff":			2,
	]),
	([      "quest":                "王五",
		"quest_type":           "杀",
		"where":		"扬州醉仙楼",
		"diff":			2,
	]),
	([      "quest":                "冼老板",
		"quest_type":           "杀",
		"where":		"扬州醉仙楼",
		"diff":			2,
	]),
	([      "quest":                "药铺伙计",
		"quest_type":           "杀",
		"where":		"药店",
		"diff":			2,
	]),
	([      "quest":                HIR"挑夫的头颅"NOR,
		"quest_type":           "寻",
		"where":		"大驿道",
		"diff":			2,
	]),
	([      "quest":                HIR"流氓的头颅"NOR,
		"quest_type":           "寻",
		"where":		"街头",
		"diff":			2,
	]),
	([      "quest":                HIR"衙役的头颅"NOR,
		"quest_type":           "寻",
		"where":		"官府",
		"diff":			2,
	]),
	([      "quest":                "关安基",
		"quest_type":           "杀",
		"where":		"北京高升茶馆",
		"diff":			2,
	]),
	([      "quest":                "屠宰场伙计",
		"quest_type":           "杀",
		"where":		"北京屠宰场",
		"diff":			2,
	]),
	([      "quest":                "喇嘛",
		"quest_type":           "杀",
		"where":		"雪山寺",
		"diff":			2,
	]),
	([      "quest":                "沈青刚",
		"quest_type":           "杀",
		"where":		"苏州以北的青石官道",
		"diff":			2,
	]),
	([      "quest":                "吴青烈",
		"quest_type":           "杀",
		"where":		"苏州以北的青石官道",
		"diff":			2,
	]),
	([      "quest":                "段天德",
		"quest_type":           "杀",
		"where":		"苏州以北的青石官道",
		"diff":			2,
	]),
	([      "quest":                "钱青健",
		"quest_type":           "杀",
		"where":		"苏州以北的青石官道",
		"diff":			2,
	]),
	([      "quest":                "侯通海",
		"quest_type":           "杀",
		"where":		"苏州以北的青石官道",
		"diff":			2,
	]),
	([      "quest":                "老虎",
		"quest_type":           "杀",
		"where":		"郊外",
		"diff":			2,
	]),
	([      "quest":                "破嗔",
		"quest_type":           "杀",
		"where":		"天龙寺",
		"diff":			2,
	]),
	([      "quest":                "东北虎",
		"quest_type":           "杀",
		"where":		"关外的密林里",
		"diff":			2,
	]),
	([      "quest":                "阎基",
		"quest_type":           "杀",
		"where":		"关外的山神庙",
		"diff":			2,
	]),
	([      "quest":                "裘千丈",
		"quest_type":           "杀",
		"where":		"归云附近的山路",
		"diff":			2,
	]),
	([      "quest":                "香火道人",
		"quest_type":           "杀",
		"where":		"杭州的青石大道",
		"diff":			2,
	]),
	([      "quest":                "哑妇",
		"quest_type":           "杀",
		"where":		"衡山悬空寺北楼",
		"diff":			2,
	]),
	([      "quest":                "校尉",
		"quest_type":           "杀",
		"where":		"灵州",
		"diff":			2,
	]),
	([      "quest":                "一品堂武士",
		"quest_type":           "杀",
		"where":		"灵州",
		"diff":			2,
	]),
	([      "quest":                "大白猿",
		"quest_type":           "杀",
		"where":		"明教昆仑仙境",
		"diff":			2,
	]),
	([      "quest":                "拓跋",
		"quest_type":           "杀",
		"where":		"明教",
		"diff":			2,
	]),
	([      "quest":                "江百胜",
		"quest_type":           "杀",
		"where":		"泰山的南天门",
		"diff":			2,
	]),
	([      "quest":                "侍童",
		"quest_type":           "杀",
		"where":		"桃花山庄",
		"diff":			2,
	]),
	([      "quest":                "哑仆",
		"quest_type":           "杀",
		"where":		"桃花山庄",
		"diff":			2,
	]),
	([      "quest":                "郭芙",
		"quest_type":           "杀",
		"where":		"襄阳城",
		"diff":			2,
	]),
	([      "quest":                "毒僵尸",
		"quest_type":           "杀",
		"where":		"星宿海",
		"diff":			2,
	]),
	([      "quest":                "杨莲亭",
		"quest_type":           "杀",
		"where":		"神龙教",
		"diff":			2,
	]),
	([      "quest":                "台夷猎人",
		"quest_type":           "杀",
		"where":		"大理附近",
		"diff":			2,
	]),
	([      "quest":                "观众戊",
		"quest_type":           "杀",
		"where":		"北京戏楼",
		"diff":			2,
	]),
	([      "quest":                "老和尚",
		"quest_type":           "杀",
		"where":		"桃源城内",
		"diff":			2,
	]),
	([      "quest":                "绿营清兵",
		"quest_type":           "杀",
		"where":		"兵营",
		"diff":			2,
	]),
	([      "quest":                "蒙面人",
		"quest_type":           "杀",
		"where":		"逍遥派",
		"diff":			2,
	]),
	([      "quest":                "剑客",
		"quest_type":           "杀",
		"where":		"泰山",
		"diff":			2,
	]),
	([      "quest":                "知客道长",
		"quest_type":           "杀",
		"where":		"武当",
		"diff":			2,
	]),
	([      "quest":                "掌园道长",
		"quest_type":           "杀",
		"where":		"武当",
		"diff":			2,
	]),
	([      "quest":                "掌经道长",
		"quest_type":           "杀",
		"where":		"武当",
		"diff":			2,
	]),
});
mapping query_quest()
{
	return quest[random(sizeof(quest))];
}
