// qlist1000.c

#include <ansi.h>
inherit SKILL;

mapping *quest = ({
	([      "quest":                HIW"纸钱"NOR,
		"quest_type":           "找",
		"where":                "桃源城的棺材店",
		"diff":                 1,
	]),
	([      "quest":                "马夫人",
		"quest_type":           "杀",
		"where":                "桃源城",
		"diff":                 1,
	]),
	([      "quest":                "艳艳",
		"quest_type":           "杀",
		"where":                "千金楼",
		"diff":                 1,
	]),
	([      "quest":                "宋承琳",
		"quest_type":           "杀",
		"where":                "千金楼",
		"diff":                 1,
	]),
	([      "quest":                "龟奴",
		"quest_type":           "杀",
		"where":                "千金楼",
		"diff":                 1,
	]),
	([      "quest":                "春红",
		"quest_type":           "杀",
		"where":                "千金楼",
		"diff":                 1,
	]),
	([      "quest":                "夏红",
		"quest_type":           "杀",
		"where":                "千金楼",
		"diff":                 1,
	]),
	([      "quest":                "冬红",
		"quest_type":           "杀",
		"where":                "千金楼",
		"diff":                 1,
	]),
	([      "quest":                "妓女",
		"quest_type":           "杀",
		"where":                "千金楼",
		"diff":                 1,
	]),
	([      "quest":                "陪酒女郎",
		"quest_type":           "杀",
		"where":                "千金楼",
		"diff":                 1,
	]),
	([      "quest":                HIW"纸花"NOR,
		"quest_type":           "找",
		"where":                "桃源城的棺材店",
		"diff":                 1,
	]),
	([      "quest":                "台夷农妇",
		"quest_type":           "杀",
		"where":                "天山附近",
		"diff":                 1,
	]),
	([      "quest":                "道童",
		"quest_type":           "杀",
		"where":                "武当",
		"diff":                 1,
	]),
	([      "quest":                HIY"黄玫瑰"NOR,
		"quest_type":           "找",
		"where":                "桃源花店",
		"diff":                 1,
	]),
	([      "quest":                HIW"白茶花"NOR,
		"quest_type":           "找",
		"where":                "桃源花店",
		"diff":                 1,
	]),
	([      "quest":                HIB"蓝天鹅"NOR,
		"quest_type":           "找",
		"where":                "桃源花店",
		"diff":                 1,
	]),
	([      "quest":                HIR"红玫瑰"NOR,
		"quest_type":           "找",
		"where":                "桃源花店",
		"diff":                 1,
	]),
	([      "quest":                BLU"黑牡丹"NOR,
		"quest_type":           "找",
		"where":                "桃源花店",
		"diff":                 1,
	]),
	([      "quest":                HIM"紫罗兰"NOR,
		"quest_type":           "找",
		"where":                "桃源花店",
		"diff":                 1,
	]),
	([      "quest":                HIC"化尸粉"NOR,
		"quest_type":           "找",
		"where":                "药店",
		"diff":                 1,
	]),
	([      "quest":                "长剑",
		"quest_type":           "找",
		"where":                "桃源的兵器铺",
		"diff":                 1,
	]),
	([      "quest":                "单刀",
		"quest_type":           "找",
		"where":                "桃源的兵器铺",
		"diff":                 1,
	]),
	([      "quest":                "钢刀",
		"quest_type":           "找",
		"where":                "桃源的兵器铺",
		"diff":                 1,
	]),
	([      "quest":                "啃得精光的鸡腿骨头",
		"quest_type":           "找",
		"where":                "客栈",
		"diff":                 1,
	]),
	([      "quest":                "牛头",
		"quest_type":           "找",
		"where":                "桃源集市肉场",
		"diff":                 1,
	]),
	([      "quest":                "猪头",
		"quest_type":           "找",
		"where":                "桃源集市肉场",
		"diff":                 1,
	]),
	([      "quest":                "猪头骨",
		"quest_type":           "找",
		"where":                "桃源集市肉场",
		"diff":                 1,
	]),
	([      "quest":                "牛头骨",
		"quest_type":           "找",
		"where":                "桃源集市肉场",
		"diff":                 1,
	]),
	([      "quest":                "短剑",
		"quest_type":           "找",
		"where":                "桃源兵器铺",
		"diff":                 1,
	]),
	([      "quest":                "睡袋",
		"quest_type":           "找",
		"where":                "杂货铺",
		"diff":                 1,
	]),
	([      "quest":                "灯笼",
		"quest_type":           "找",
		"where":                "杂货铺",
		"diff":                 1,
	]),
	([      "quest":                "草鞋",
		"quest_type":           "找",
		"where":                "扬州成衣店",
		"diff":                 1,
	]),
	([      "quest":                "布衣",
		"quest_type":           "找",
		"where":                "扬州成衣店",
		"diff":                 1,
	]),
	([      "quest":                HIG"玉指"NOR,
		"quest_type":           "找",
		"where":                "桃源珠宝店",
		"diff":                 1,
	]),
	([      "quest":                "雄黄",
		"quest_type":           "找",
		"where":                "药店",
		"diff":                 1,
	]),
	([      "quest":                HIW"大石头"NOR,
		"quest_type":           "找",
		"where":                "扬州树林",
		"diff":                 1,
	]),
	([      "quest":                "大树枝",
		"quest_type":           "找",
		"where":                "扬州树林",
		"diff":                 1,
	]),
	([      "quest":                "毒蛇",
		"quest_type":           "杀",
		"where":                "扬州树林",
		"diff":                 1,
	]),
	([      "quest":                "阿庆嫂",
		"quest_type":           "杀",
		"where":                "扬州春来茶馆",
		"diff":                 1,
	]),
	([      "quest":                "小混混",
		"quest_type":           "杀",
		"where":                "扬州",
		"diff":                 1,
	]),
	([      "quest":                "托钵僧",
		"quest_type":           "杀",
		"where":                "扬州",
		"diff":                 1,
	]),
	([      "quest":                "茅十八",
		"quest_type":           "杀",
		"where":                "扬州",
		"diff":                 1,
	]),
});
mapping query_quest()
{
	return quest[random(sizeof(quest))];
}
