// qlist20000.c

#include <ansi.h>

inherit SKILL;

mapping *quest = ({
	([      "quest":                HIM"紫绫纱湘裙"NOR,
		"quest_type":           "找",
		"where":                "扬州城的成衣店",
		"diff":                 1,
	]),
	([      "quest":                HIY"富贵团金褂"NOR,
		"quest_type":           "找",
		"where":                "扬州城的成衣店",
		"diff":                 1,
	]),
	([      "quest":                HIK"玄色紧身袄"NOR,
		"quest_type":           "找",
		"where":                "扬州城的成衣店",
		"diff":                 1,
	]),
	([      "quest":                HIY"软金束带"NOR,
		"quest_type":           "找",
		"where":                "扬州城的成衣店",
		"diff":                 1,
	]),
	([      "quest":                HIB"一字逍遥巾"NOR,
		"quest_type":           "找",
		"where":                "扬州城的成衣店",
		"diff":                 1,
	]),
	([      "quest":                HIM"五彩绣花裙"NOR,
		"quest_type":           "找",
		"where":                "扬州城的成衣店",
		"diff":                 1,
	]),
	([      "quest":                HIW"琼花皎月裳"NOR,
		"quest_type":           "找",
		"where":                "扬州城的成衣店",
		"diff":                 1,
	]),
	([      "quest":                RED"艳露凝香衣"NOR,
		"quest_type":           "找",
		"where":                "扬州城的成衣店",
		"diff":                 1,
	]),
	([      "quest":                HIG"养精丹"NOR,
		"quest_type":           "找",
		"where":                "扬州城的药店",
		"diff":                 1,
	]),
	([      "quest":                HIR"无常丹"NOR,
		"quest_type":           "找",
		"where":                "扬州城的药店",
		"diff":                 1,
	]),
	([      "quest":                "兔肉",
		"quest_type":           "找",
		"where":                "桃源城的小树林",
		"diff":                 1,
	]),
	([      "quest":                "地痞",
		"quest_type":           "杀",
		"where":                "长安杨柳胡同",
		"diff":                 1,
	]),
	([      "quest":                "小猴",
		"quest_type":           "杀",
		"where":                "峨嵋山的九老洞口",
		"diff":                 1,
	]),
	([      "quest":                "张妈",
		"quest_type":           "杀",
		"where":                "白驼山庄的厨房",
		"diff":                 1,
	]),
	([      "quest":                "白衣少女",
		"quest_type":           "杀",
		"where":                "大理附近",
		"diff":                 1,
	]),
	([      "quest":                "游客",
		"quest_type":           "杀",
		"where":                "大理碧鸡山顶",
		"diff":                 1,
	]),
	([      "quest":                "流氓",
		"quest_type":           "杀",
		"where":                "扬州中央广场",
		"diff":                 1,
	]),
	([      "quest":                "绣花针",
		"quest_type":           "找",
		"where":                "杂货店",
		"diff":                 1,
	]),
	([      "quest":                "小孩",
		"quest_type":           "杀",
		"where":                "武功镇北街",
		"diff":                 1,
	]),
	([      "quest":                RED"东坡肉"NOR,
		"quest_type":           "找",
		"where":                "杭州楼外楼",
		"diff":                 1,
	]),
	([      "quest":                "酒瓶",
		"quest_type":           "找",
		"where":                "杭州楼外楼",
		"diff":                 1,
	]),
	([      "quest":                HIY"理气丸"NOR,
		"quest_type":           "找",
		"where":                "桃源药店",
		"diff":                 1,
	]),
	([      "quest":                "小偷",
		"quest_type":           "杀",
		"where":                "桃源城",
		"diff":                 1,
	]),
	([      "quest":                "靴子",
		"quest_type":           "找",
		"where":                "成衣店",
		"diff":                 1,
	]),
	([      "quest":                "衙役服",
		"quest_type":           "找",
		"where":                "衙门",
		"diff":                 1,
	]),
	([      "quest":                "苏州少女",
		"quest_type":           "杀",
		"where":                "苏州茶馆",
		"diff":                 1,
	]),
	([      "quest":                HIG"养精丹"NOR,
		"quest_type":           "找",
		"where":                "药铺",
		"diff":                 1,
	]),
});
mapping query_quest()
{
	return quest[random(sizeof(quest))];
}
