// qlist50000.c

inherit SKILL;
#include <ansi.h>
mapping *quest = ({
	([      "quest":                "龟奴",
		"quest_type":           "杀",
		"where":		"桃源的千金楼",
		"diff":			1,
	]),
	([      "quest":                "皮条客",
		"quest_type":           "杀",
		"where":		"桃源的千金楼",
		"diff":			1,
	]),
	([      "quest":                "陪酒女郎",
		"quest_type":           "杀",
		"where":		"桃源的千金楼",
		"diff":			1,
	]),
	([      "quest":                "舞女",
		"quest_type":           "杀",
		"where":		"桃源城的千金楼",
		"diff":			1,
	]),
	([      "quest":                "香香",
		"quest_type":           "杀",
		"where":		"桃源客栈",
		"diff":			1,
	]),
	([      "quest":                "老和尚",
		"quest_type":           "杀",
		"where":		"桃源或扬州",
		"diff":			1,
	]),
	([      "quest":                "兵丁服",
		"quest_type":           "找",
		"where":		"桃源布庄",
		"diff":			1,
	]),
	([      "quest":                "战靴",
		"quest_type":           "找",
		"where":		"桃源布庄",
		"diff":			1,
	]),
	([      "quest":                "布鞋",
		"quest_type":           "找",
		"where":		"桃源布庄",
		"diff":			1,
	]),
	([      "quest":                "竹笠",
		"quest_type":           "找",
		"where":		"桃源布庄",
		"diff":			1,
	]),
	([      "quest":                HIB"蓝布衫"NOR,
		"quest_type":           "找",
		"where":		"桃源布庄",
		"diff":			1,
	]),
	([      "quest":                "杨老四",
		"quest_type":           "杀",
		"where":		"桃源布庄",
		"diff":			1,
	]),
	([      "quest":                "进香客",
		"quest_type":           "杀",
		"where":		"雪山附近",
		"diff":			1,
	]),
	([      "quest":                "崔镖头",
		"quest_type":           "杀",
		"where":		"福州西门大街",
		"diff":			1,
	]),
	([      "quest":                HIW"玉蜂"NOR,
		"quest_type":           "杀",
		"where":		"古墓派的墓门",
		"diff":			1,
	]),
	([      "quest":                "巴依",
		"quest_type":           "杀",
		"where":		"天山附近",
		"diff":			1,
	]),
	([      "quest":                "买卖提",
		"quest_type":           "杀",
		"where":		"天山附近",
		"diff":			1,
	]),
	([      "quest":                "秋红",
		"quest_type":           "杀",
		"where":		"桃源城千金楼",
		"diff":			1,
	]),
	([      "quest":                "维吾尔族妇女",
		"quest_type":           "杀",
		"where":		"天山附近",
		"diff":			1,
	]),
	([      "quest":                "阿凡提",
		"quest_type":           "杀",
		"where":		"天山附近",
		"diff":			1,
	]),
	([      "quest":                "拳法入门",
		"quest_type":           "找",
		"where":		"桃源书屋",
		"diff":			1,
	]),
	([      "quest":                "拳法进阶",
		"quest_type":           "找",
		"where":		"桃源书屋",
		"diff":			1,
	]),
	([      "quest":                "拳法精要",
		"quest_type":           "找",
		"where":		"桃源书屋",
		"diff":			1,
	]),
	([      "quest":                "拳法总诀",
		"quest_type":           "找",
		"where":		"桃源书屋",
		"diff":			1,
	]),
	([      "quest":                "手法入门",
		"quest_type":           "找",
		"where":		"桃源书屋",
		"diff":			1,
	]),
	([      "quest":                "手法进阶",
		"quest_type":           "找",
		"where":		"桃源书屋",
		"diff":			1,
	]),
	([      "quest":                "手法精要",
		"quest_type":           "找",
		"where":		"桃源书屋",
		"diff":			1,
	]),
	([      "quest":                "手法总诀",
		"quest_type":           "找",
		"where":		"桃源书屋",
		"diff":			1,
	]),
	([      "quest":                "剑法入门",
		"quest_type":           "找",
		"where":		"桃源书屋",
		"diff":			1,
	]),
	([      "quest":                "剑法进阶",
		"quest_type":           "找",
		"where":		"桃源书屋",
		"diff":			1,
	]),
	([      "quest":                "剑法精要",
		"quest_type":           "找",
		"where":		"桃源书屋",
		"diff":			1,
	]),
	([      "quest":                "剑法总诀",
		"quest_type":           "找",
		"where":		"桃源书屋",
		"diff":			1,
	]),
	([      "quest":                "心法入门",
		"quest_type":           "找",
		"where":		"桃源书屋",
		"diff":			1,
	]),
	([      "quest":                "心法进阶",
		"quest_type":           "找",
		"where":		"桃源书屋",
		"diff":			1,
	]),
	([      "quest":                "屠刀",
		"quest_type":           "找",
		"where":		"扬州打铁铺",
		"diff":			1,
	]),
	([      "quest":                "铁甲",
		"quest_type":           "找",
		"where":		"扬州打铁铺",
		"diff":			1,
	]),
	([      "quest":                "匕首",
		"quest_type":           "找",
		"where":		"扬州打铁铺",
		"diff":			1,
	]),
	([      "quest":                "铁锤",
		"quest_type":           "找",
		"where":		"扬州打铁铺",
		"diff":			1,
	]),
	([      "quest":                "长剑",
		"quest_type":           "找",
		"where":		"扬州打铁铺",
		"diff":			1,
	]),
	([      "quest":                "铁棍",
		"quest_type":           "找",
		"where":		"扬州打铁铺",
		"diff":			1,
	]),
	([      "quest":                "指套",
		"quest_type":           "找",
		"where":		"扬州杂货铺",
		"diff":			1,
	]),
	([      "quest":                "麻布袋",
		"quest_type":           "找",
		"where":		"扬州杂货铺",
		"diff":			1,
	]),
	([      "quest":                "灯笼",
		"quest_type":           "找",
		"where":		"扬州杂货铺",
		"diff":			1,
	]),
	([      "quest":                "睡袋",
		"quest_type":           "找",
		"where":		"扬州杂货铺",
		"diff":			1,
	]),
	([      "quest":                "草鞋",
		"quest_type":           "找",
		"where":		"扬州杂货铺",
		"diff":			1,
	]),
	([      "quest":                "护腰",
		"quest_type":           "找",
		"where":		"扬州杂货铺",
		"diff":			1,
	]),
	([      "quest":                "护腕",
		"quest_type":           "找",
		"where":		"扬州杂货铺",
		"diff":			1,
	]),
	([      "quest":                "牛皮盾",
		"quest_type":           "找",
		"where":		"扬州杂货铺",
		"diff":			1,
	]),
	([      "quest":                "铁手掌",
		"quest_type":           "找",
		"where":		"扬州杂货铺",
		"diff":			1,
	]),
	([      "quest":                "肚带",
		"quest_type":           "找",
		"where":		"扬州杂货铺",
		"diff":			1,
	]),
	([      "quest":                "皮手套",
		"quest_type":           "找",
		"where":		"扬州杂货铺",
		"diff":			1,
	]),
	([      "quest":                "武者项圈",
		"quest_type":           "找",
		"where":		"扬州杂货铺",
		"diff":			1,
	]),
	([      "quest":                "皮靴",
		"quest_type":           "找",
		"where":		"扬州杂货铺",
		"diff":			1,
	]),
	([      "quest":                "皮背心",
		"quest_type":           "找",
		"where":		"扬州杂货铺",
		"diff":			1,
	]),
	([      "quest":                "头盔",
		"quest_type":           "找",
		"where":		"扬州杂货铺",
		"diff":			1,
	]),
	([      "quest":                "五香花生",
		"quest_type":           "找",
		"where":		"扬州春来茶馆",
		"diff":			1,
	]),
	([      "quest":                "翡翠豆腐",
		"quest_type":           "找",
		"where":		"扬州春来茶馆",
		"diff":			1,
	]),
	([      "quest":                "面",
		"quest_type":           "找",
		"where":		"扬州客店",
		"diff":			1,
	]),
	([      "quest":                "啃得精光的鸡腿骨头",
		"quest_type":           "找",
		"where":		"扬州客店",
		"diff":			1,
	]),
	([      "quest":                HIM"粉红绸衫"NOR,
		"quest_type":           "找",
		"where":		"成衣店",
		"diff":			1,
	]),
	([      "quest":                HIG"青绫绸裙"NOR,
		"quest_type":           "找",
		"where":		"成衣店",
		"diff":			1,
	]),
	([      "quest":                RED"霓红连衣裙"NOR,
		"quest_type":           "找",
		"where":		"成衣店",
		"diff":			1,
	]),
	([      "quest":                HIR"大红袈裟"NOR,
		"quest_type":           "找",
		"where":		"扬州城老和尚处",
		"diff":			1,
	]),
	([      "quest":                "长剑",
		"quest_type":           "找",
		"where":		"兵器铺",
		"diff":			1,
	]),
	([      "quest":                "锦缎",
		"quest_type":           "找",
		"where":		"北京熬拜府",
		"diff":			1,
	]),
	([      "quest":                HIR"匕首"NOR,
		"quest_type":           "找",
		"where":		"熬拜府",
		"diff":			1,
	]),
	([      "quest":                "夜明珠",
		"quest_type":           "找",
		"where":		"嘉兴南湖",
		"diff":			1,
	]),
});
mapping query_quest()
{
	return quest[random(sizeof(quest))];
}
