// qlist1000.c

#include <ansi.h>
inherit SKILL;

mapping *quest = ({
	([      "quest":                "家丁",
		"quest_type":           "杀",
		"where": 		"富豪大院",
		"diff":			1,
	]),
	([      "quest":                "凤天南",
		"quest_type":           "杀",
		"where":		"桃源城的戏楼",
		"diff":			1,
	]),
	([      "quest":                "蜜蜂",
		"quest_type":           "杀",
		"where":		"桃源城外的大官道",
		"diff":			1,
	]),
	([      "quest":                "长工",
		"quest_type":           "杀",
		"where":		"富豪大院",
		"diff":			1,
	]),
	([      "quest":                "张夫人",
		"quest_type":           "杀",
		"where":		"富豪大院",
		"diff":			1,
	]),
	([      "quest":                "麻雀",
		"quest_type":           "杀",
		"where":		"桃源大槐树园",
		"diff":			1,
	]),
	([      "quest":                "铁匠",
		"quest_type":           "杀",
		"where":		"扬州城打铁铺",
		"diff":			1,
	]),
	([      "quest":                HIG"草鱼"NOR,
		"quest_type":           "找",
		"where":		"扬州城以北的钓鱼台",
		"diff":			1,
	]),
	([      "quest":                HIR"大红鲤鱼"NOR,
		"quest_type":           "找",
		"where":		"扬州城以北的钓鱼台",
		"diff":			1,
	]),
	([      "quest":                HIY"鲤鱼"NOR,
		"quest_type":           "找",
		"where":		"扬州城以北的钓鱼台",
		"diff":			1,
	]),
	([      "quest":                HIY"娃娃鱼"NOR,
		"quest_type":           "找",
		"where":		"扬州城以北的钓鱼台",
		"diff":			1,
	]),
	([      "quest":                WHT"罗非"NOR,
		"quest_type":           "找",
		"where":		"扬州城以北的钓鱼台",
		"diff":			1,
	]),
	([      "quest":                YEL"莲鱼"NOR,
		"quest_type":           "找",
		"where":		"扬州城以北的钓鱼台",
		"diff":			1,
	]),
	([      "quest":                "牛皮酒袋",
		"quest_type":           "找",
		"where":		"客栈",
		"diff":			1,
	]),
	([      "quest":                HIR"结婚礼服"NOR,
		"quest_type":           "找",
		"where":		"扬州城的成衣店",
		"diff":			1,
	]),


});

mapping query_quest()
{
	return quest[random(sizeof(quest))];
}
