// qlist300000.c
#include <ansi.h>
inherit SKILL;

mapping *quest = ({
	([      "quest":                "明珠",
		"quest_type":           "寻",
		"where":                "桃花岛",
		"diff":                 3,
	]),
	([      "quest":                "拳谱总诀",
		"quest_type":           "寻",
		"where":                "逍遥派",
		"diff":                 3,
	]),
	([      "quest":                "掌法总谱",
		"quest_type":           "寻",
		"where":                "燕子坞",
		"diff":                 3,
	]),
	([      "quest":                "棋谱",
		"quest_type":           "寻",
		"where":                "逍遥派",
		"diff":                 3,
	]),
	([      "quest":                "玉女剑谱",
		"quest_type":           "寻",
		"where":                "古墓派",
		"diff":                 3,
	]),
	([      "quest":                "天山器法",
		"quest_type":           "寻",
		"where":                "星宿海",
		"diff":                 3,
	]),
	([      "quest":                "圣火令",
		"quest_type":           "寻",
		"where":                "明教",
		"diff":                 3,
	]),
	([      "quest":                "萧飞",
		"quest_type":           "杀",
		"where":                "成都武馆",
		"diff":                 3,
	]),
	([      "quest":                "家丁",
		"quest_type":           "杀",
		"where":                "富豪大院",
		"diff":                 3,
	]),
	([      "quest":                "柯镇恶",
		"quest_type":           "杀",
		"where":                "归云山庄",
		"diff":                 3,
	]),
	([      "quest":                "高彦超",
		"quest_type":           "杀",
		"where":                "北京",
		"diff":                 3,
	]),
	([      "quest":                "仪文",
		"quest_type":           "杀",
		"where":                "恒山",
		"diff":                 3,
	]),
	([      "quest":                "邓八年",
		"quest_type":           "杀",
		"where":                "嵩山",
		"diff":                 3,
	]),
	([      "quest":                "李嫂",
		"quest_type":           "杀",
		"where":                "灵鹫宫",
		"diff":                 3,
	]),
	([      "quest":                "木人",
		"quest_type":           "杀",
		"where":                "少林寺",
		"diff":                 3,
	]),
	([      "quest":                "武馆弟子",
		"quest_type":           "杀",
		"where":                "武馆",
		"diff":                 3,
	]),
	([      "quest":                "机关人",
		"quest_type":           "杀",
		"where":                "桃花岛",
		"diff":                 3,
	]),
	([      "quest":                "林平之",
		"quest_type":           "杀",
		"where":                "小树林",
		"diff":                 3,
	]),
	([      "quest":                "竹人",
		"quest_type":           "杀",
		"where":                "唐门",
		"diff":                 3,
	]),
	([      "quest":                "唐门弟子",
		"quest_type":           "杀",
		"where":                "唐家堡",
		"diff":                 3,
	]),
	([      "quest":                "木人",
		"quest_type":           "杀",
		"where":                "少林寺",
		"diff":                 3,
	]),
	([      "quest":                "唐无火",
		"quest_type":           "杀",
		"where":                "唐门",
		"diff":                 3,
	]),
	([      "quest":                HIB"蕙兰花"NOR,
		"quest_type":           "寻",
		"where":                "泉州郊外",
		"diff":                 3,
	]),
	([      "quest":                "李志常",
		"quest_type":           "杀",
		"where":                "全真教",
		"diff":                 3,
	]),
	([      "quest":                "崔志方",
		"quest_type":           "杀",
		"where":                "全真教",
		"diff":                 3,
	]),
	([      "quest":                "王处一",
		"quest_type":           "杀",
		"where":                "全真教",
		"diff":                 3,
	]),
	([      "quest":                "申志凡",
		"quest_type":           "杀",
		"where":                "全真教",
		"diff":                 3,
	]),
	([      "quest":                "房志起",
		"quest_type":           "杀",
		"where":                "全真教",
		"diff":                 3,
	]),
	([      "quest":                "神龙教老者",
		"quest_type":           "杀",
		"where":                "神龙教",
		"diff":                 3,
	]),
	([      "quest":                "无根道长",
		"quest_type":           "杀",
		"where":                "神龙教",
		"diff":                 3,
	]),
	([      "quest":                "张淡月",
		"quest_type":           "杀",
		"where":                "神龙教",
		"diff":                 3,
	]),
	([      "quest":                "木人",
		"quest_type":           "杀",
		"where":                "神龙教",
		"diff":                 3,
	]),
});

mapping query_quest()
{
	return quest[random(sizeof(quest))];
}
