// qlist1200000.c

inherit SKILL;

#include <ansi.h>

mapping *quest = ({
	([      "quest":                "定闲师太",
		"quest_type":           "杀",
		"where":                "恒山派",
		"diff":                 6,
	]),
	([      "quest":                "莫大",
		"quest_type":           "杀",
		"where":                "衡山派",
		"diff":                 6,
	]),
	([      "quest":                "左冷禅",
		"quest_type":           "杀",
		"where":                "泰山派",
		"diff":                 6,
	]),
	([      "quest":                "天门道人",
		"quest_type":           "杀",
		"where":                "泰山派",
		"diff":                 6,
	]),
	([      "quest":                "袁紫衣",
		"quest_type":           "杀",
		"where":                "恒山派",
		"diff":                 6,
	]),
	([      "quest":                "龙亦凡",
		"quest_type":           "杀",
		"where":                "侠客岛",
		"diff":                 6,
	]),
	([      "quest":                "木丹凤",
		"quest_type":           "杀",
		"where":                "侠客岛",
		"diff":                 6,
	]),
	([      "quest":                "谢烟客",
		"quest_type":           "杀",
		"where":                "侠客岛",
		"diff":                 6,
	]),
	([      "quest":                "刑部狱卒",
		"quest_type":           "杀",
		"where":                "北京城",
		"diff":                 6,
	]),
	([      "quest":                "欧冶子",
		"quest_type":           "杀",
		"where":                "铸剑室",
		"diff":                 6,
	]),
	([      "quest":                "萧秋水",
		"quest_type":           "杀",
		"where":                "唐门",
		"diff":                 6,
	]),
	([      "quest":                "陆高轩",
		"quest_type":           "杀",
		"where":                "神龙教",
		"diff":                 6,
	]),
	([      "quest":                "本观",
		"quest_type":           "杀",
		"where":                "天龙寺",
		"diff":                 6,
	]),
	([      "quest":                "唐猛",
		"quest_type":           "杀",
		"where":                "唐门",
		"diff":                 6,
	]),
	([      "quest":                "马超兴",
		"quest_type":           "杀",
		"where":                "扬州城门",
		"diff":                 6,
	]),
	([      "quest":                HIM"淑女剑"NOR,
		"quest_type":           "找",
		"where":                "古墓派",
		"diff":                 6,
	]),
	([      "quest":                HIC"玄铁重剑"NOR,
		"quest_type":           "找",
		"where":                "古墓派",
		"diff":                 6,
	]),
	([      "quest":                "紫霞密芨",
		"quest_type":           "找",
		"where":                "华山派",
		"diff":                 6,
	]),
	([      "quest":                "紫霞密芨",
		"quest_type":           "找",
		"where":                "华山派",
		"diff":                 6,
	]),
	([      "quest":                HIG"碧水剑"NOR,
		"quest_type":           "找",
		"where":                "华山派",
		"diff":                 6,
	]),
	([      "quest":                YEL"黄米饭"NOR,
		"quest_type":           "找",
		"where":                "华山派厨房",
		"diff":                 6,
	]),
	([      "quest":                MAG"汤碗"NOR,
		"quest_type":           "找",
		"where":                "华山派厨房",
		"diff":                 6,
	]),
});
mapping query_quest()
{
	return quest[random(sizeof(quest))];
}