// qlist50000.c

inherit SKILL;

#include <ansi.h>

mapping *quest = ({
	([      "quest":                "烤鸭",
		"quest_type":           "找",
		"where":                "客店",
		"diff":                 1,
	]),
	([      "quest":                "牛皮酒袋",
		"quest_type":           "找",
		"where":                "客店",
		"diff":                 1,
	]),
	([      "quest":                "烤鸡腿",
		"quest_type":           "找",
		"where":                "客店",
		"diff":                 1,
	]),
	([      "quest":                "面",
		"quest_type":           "找",
		"where":                "客店",
		"diff":                 1,
	]),
	([      "quest":                "牛头骨",
		"quest_type":           "找",
		"where":                "集市肉场",
		"diff":                 1,
	]),
	([      "quest":                "手法入门",
		"quest_type":           "找",
		"where":                "桃源书屋",
		"diff":                 1,
	]),
	([      "quest":                "手法进阶",
		"quest_type":           "找",
		"where":                "桃源书屋",
		"diff":                 1,
	]),
	([      "quest":                "手法精要",
		"quest_type":           "找",
		"where":                "桃源书屋",
		"diff":                 1,
	]),
	([      "quest":                "手法总诀",
		"quest_type":           "找",
		"where":                "桃源书屋",
		"diff":                 1,
	]),
	([      "quest":                "剑法入门",
		"quest_type":           "找",
		"where":                "桃源书屋",
		"diff":                 1,
	]),
	([      "quest":                "剑法进阶",
		"quest_type":           "找",
		"where":                "桃源书屋",
		"diff":                 1,
	]),
	([      "quest":                "剑法精要",
		"quest_type":           "找",
		"where":                "桃源书屋",
		"diff":                 1,
	]),
	([      "quest":                "剑法总诀",
		"quest_type":           "找",
		"where":                "桃源书屋",
		"diff":                 1,
	]),
	([      "quest":                "心法入门",
		"quest_type":           "找",
		"where":                "桃源书屋",
		"diff":                 1,
	]),
	([      "quest":                "心法进阶",
		"quest_type":           "找",
		"where":                "桃源书屋",
		"diff":                 1,
	]),
	([      "quest":                "心法精要",
		"quest_type":           "找",
		"where":                "桃源书屋",
		"diff":                 1,
	]),
	([      "quest":                "心法总诀",
		"quest_type":           "找",
		"where":                "桃源书屋",
		"diff":                 1,
	]),
	([      "quest":                "闪躲入门",
		"quest_type":           "找",
		"where":                "桃源书屋",
		"diff":                 1,
	]),
	([      "quest":                "闪躲进阶",
		"quest_type":           "找",
		"where":                "桃源书屋",
		"diff":                 1,
	]),
	([      "quest":                "公子哥",
		"quest_type":           "杀",
		"where":                "苏州书场",
		"diff":                 1,
	]),
	([      "quest":                "尼姑",
		"quest_type":           "杀",
		"where":                "苏州紫金庵",
		"diff":                 1,
	]),
	([      "quest":                "婢女",
		"quest_type":           "杀",
		"where":                "苏州问梅阁",
		"diff":                 1,
	]),
	([      "quest":                HIG"手镯"NOR,
		"quest_type":           "找",
		"where":                "北京鳌拜府",
		"diff":                 1,
	]),
	([      "quest":                HIC"玉佩"NOR,
		"quest_type":           "找",
		"where":                "北京鳌拜府",
		"diff":                 1,
	]),
	([      "quest":                "金叶",
		"quest_type":           "找",
		"where":                "北京鳌拜府",
		"diff":                 1,
	]),
	([      "quest":                "夜明珠",
		"quest_type":           "找",
		"where":                "嘉兴南湖",
		"diff":                 1,
	]),
	([      "quest":                HIR"赤血刀"NOR,
		"quest_type":           "找",
		"where":                "血刀门",
		"diff":                 1,
	]),
	([      "quest":                "蛮刀",
		"quest_type":           "找",
		"where":                "大理",
		"diff":                 1,
	]),
	([      "quest":                "虎皮",
		"quest_type":           "找",
		"where":                "大理",
		"diff":                 1,
	]),
	([      "quest":                "熊胆干",
		"quest_type":           "找",
		"where":                "关外",
		"diff":                 1,
	]),
	([      "quest":                "道藏真卷",
		"quest_type":           "找",
		"where":                "城隍庙",
		"diff":                 1,
	]),
	([      "quest":                "佛法真卷",
		"quest_type":           "找",
		"where":                "城隍庙",
		"diff":                 1,
	]),
	([      "quest":                "道家学说四集",
		"quest_type":           "找",
		"where":                "城隍庙",
		"diff":                 1,
	]),
	([      "quest":                "大乘佛法四集",
		"quest_type":           "找",
		"where":                "城隍庙",
		"diff":                 1,
	]),
	([      "quest":                "道家学说三集",
		"quest_type":           "找",
		"where":                "城隍庙",
		"diff":                 1,
	]),
	([      "quest":                "大乘佛法三集",
		"quest_type":           "找",
		"where":                "城隍庙",
		"diff":                 1,
	]),
	([      "quest":                "道家学说二集",
		"quest_type":           "找",
		"where":                "城隍庙",
		"diff":                 1,
	]),
	([      "quest":                "大乘佛法二集",
		"quest_type":           "找",
		"where":                "城隍庙",
		"diff":                 1,
	]),
	([      "quest":                "道家学说一集",
		"quest_type":           "找",
		"where":                "城隍庙",
		"diff":                 1,
	]),
	([      "quest":                "大乘佛法一集",
		"quest_type":           "找",
		"where":                "城隍庙",
		"diff":                 1,
	]),
	([      "quest":                HIC"小龙泉"NOR,
		"quest_type":           "找",
		"where":                "兵器铺",
		"diff":                 1,
	]),
	([      "quest":                HIW"飞刀"NOR,
		"quest_type":           "找",
		"where":                "兵器铺",
		"diff":                 1,
	]),
	([      "quest":                YEL"铜钱镖"NOR,
		"quest_type":           "找",
		"where":                "兵器铺",
		"diff":                 1,
	]),
	([      "quest":                "千年灵芝",
		"quest_type":           "找",
		"where":                "桃源回春堂",
		"diff":                 1,
	]),
	([      "quest":                HIY"金创药"NOR,
		"quest_type":           "找",
		"where":                "桃源回春堂",
		"diff":                 1,
	]),
	([      "quest":                "荷兰火枪",
		"quest_type":           "找",
		"where":                "泉州",
		"diff":                 1,
	]),
	([      "quest":                RED"大鬃马"NOR,
		"quest_type":           "找",
		"where":                "车马店",
		"diff":                 1,
	]),
	([      "quest":                RED"西湖醋鱼"NOR,
		"quest_type":           "找",
		"where":                "杭州楼外楼",
		"diff":                 1,
	]),
	([      "quest":                YEL"叫化童鸡"NOR,
		"quest_type":           "找",
		"where":                "杭州楼外楼",
		"diff":                 1,
	]),
	([      "quest":                RED"龙井虾仁"NOR,
		"quest_type":           "找",
		"where":                "杭州楼外楼",
		"diff":                 1,
	]),
	([      "quest":                HIR"桂花鲜栗羹"NOR,
		"quest_type":           "找",
		"where":                "杭州楼外楼",
		"diff":                 1,
	]),
	([      "quest":                HIY"百果油包"NOR,
		"quest_type":           "找",
		"where":                "杭州楼外楼",
		"diff":                 1,
	]),
	([      "quest":                "貂皮",
		"quest_type":           "找",
		"where":                "北京城",
		"diff":                 1,
	]),
	([      "quest":                "薄绢",
		"quest_type":           "找",
		"where":                "侠客岛",
		"diff":                 1,
	]),
	([      "quest":                "削刀",
		"quest_type":           "找",
		"where":                "泉州棺材店",
		"diff":                 1,
	]),
	([      "quest":                HIY"真丝宝甲"NOR,
		"quest_type":           "找",
		"where":                "北京鳌拜府",
		"diff":                 1,
	]),
	([      "quest":                "牛皮盾",
		"quest_type":           "找",
		"where":                "扬州杂货店",
		"diff":                 1,
	]),
	([      "quest":                "灯笼",
		"quest_type":           "找",
		"where":                "扬州杂货店",
		"diff":                 1,
	]),
	([      "quest":                HIY"金丝甲"NOR,
		"quest_type":           "找",
		"where":                "扬州杂货店",
		"diff":                 1,
	]),
	([      "quest":                HIW"巴豆"NOR,
		"quest_type":           "找",
		"where":                "济世堂老店",
		"diff":                 1,
	]),
	([      "quest":                WHT"白术"NOR,
		"quest_type":           "找",
		"where":                "济世堂老店",
		"diff":                 1,
	]),
	([      "quest":                MAG"豹胎"NOR,
		"quest_type":           "找",
		"where":                "济世堂老店",
		"diff":                 1,
	]),
	([      "quest":                YEL"蝉蜕"NOR,
		"quest_type":           "找",
		"where":                "济世堂老店",
		"diff":                 1,
	]),
	([      "quest":                HIY"川贝"NOR,
		"quest_type":           "找",
		"where":                "济世堂老店",
		"diff":                 1,
	]),
	([      "quest":                YEL"穿山甲"NOR,
		"quest_type":           "找",
		"where":                "济世堂老店",
		"diff":                 1,
	]),
	([      "quest":                HIB"断血草"NOR,
		"quest_type":           "找",
		"where":                "济世堂老店",
		"diff":                 1,
	]),
	([      "quest":                YEL"防风"NOR,
		"quest_type":           "找",
		"where":                "济世堂老店",
		"diff":                 1,
	]),
	([      "quest":                HIG"茯苓"NOR,
		"quest_type":           "找",
		"where":                "济世堂老店",
		"diff":                 1,
	]),
	([      "quest":                HIG"甘草"NOR,
		"quest_type":           "找",
		"where":                "济世堂老店",
		"diff":                 1,
	]),
	([      "quest":                HIR"枸枳子"NOR,
		"quest_type":           "找",
		"where":                "济世堂老店",
		"diff":                 1,
	]),
	([      "quest":                HIY"何首乌"NOR,
		"quest_type":           "找",
		"where":                "济世堂老店",
		"diff":                 1,
	]),
	([      "quest":                HIG"荷叶"NOR,
		"quest_type":           "找",
		"where":                "济世堂老店",
		"diff":                 1,
	]),
	([      "quest":                HIR"红花"NOR,
		"quest_type":           "找",
		"where":                "济世堂老店",
		"diff":                 1,
	]),
	([      "quest":                HIY"黄连"NOR,
		"quest_type":           "找",
		"where":                "济世堂老店",
		"diff":                 1,
	]),
	([      "quest":                YEL"金钱草"NOR,
		"quest_type":           "找",
		"where":                "济世堂老店",
		"diff":                 1,
	]),
	([      "quest":                HIY"金"HIW"银"HIC"花"NOR,
		"quest_type":           "找",
		"where":                "济世堂老店",
		"diff":                 1,
	]),
	([      "quest":                HIY"菊梗"NOR,
		"quest_type":           "找",
		"where":                "济世堂老店",
		"diff":                 1,
	]),
});
mapping query_quest()
{
	return quest[random(sizeof(quest))];
}