// qlist100000.c

inherit SKILL;

#include <ansi.h>

mapping *quest = ({
	([      "quest":                "小沙弥",
		"quest_type":           "杀",
		"where":                "天龙寺",
		"diff":                 2,
	]),
	([      "quest":                "护塔僧",
		"quest_type":           "杀",
		"where":                "天龙寺",
		"diff":                 2,
	]),
	([      "quest":                "老年僧人",
		"quest_type":           "杀",
		"where":                "天龙寺",
		"diff":                 2,
	]),
	([      "quest":                "守寺僧兵",
		"quest_type":           "杀",
		"where":                "雪山寺",
		"diff":                 2,
	]),
	([      "quest":                "托钵僧",
		"quest_type":           "杀",
		"where":                "扬州城内",
		"diff":                 2,
	]),
	([      "quest":                "肥肥",
		"quest_type":           "杀",
		"where":                "白驼山庄的厨房",
		"diff":                 2,
	]),
	([      "quest":                "乌鸦",
		"quest_type":           "杀",
		"where":                "郊外",
		"diff":                 2,
	]),
	([      "quest":                "松鼠",
		"quest_type":           "杀",
		"where":                "桃源城的小树林",
		"diff":                 2,
	]),
	([      "quest":                "大狼狗",
		"quest_type":           "杀",
		"where":                "财主大门",
		"diff":                 2,
	]),
	([      "quest":                "大刀",
		"quest_type":           "寻",
		"where":                "兵器铺",
		"diff":                 2,
	]),
	([      "quest":                "小喇嘛",
		"quest_type":           "杀",
		"where":                "雪山寺",
		"diff":                 2,
	]),
	([      "quest":                "道童",
		"quest_type":           "杀",
		"where":                "武当藏经阁",
		"diff":                 2,
	]),
	([      "quest":                "仆人",
		"quest_type":           "杀",
		"where":                "桃花山庄",
		"diff":                 2,
	]),
	([      "quest":                "镖头",
		"quest_type":           "杀",
		"where":                "镖局",
		"diff":                 2,
	]),
	([      "quest":                "刀客",
		"quest_type":           "杀",
		"where":                "泰山",
		"diff":                 2,
	]),
	([      "quest":                "趟子手",
		"quest_type":           "杀",
		"where":                "桃源城内",
		"diff":                 2,
	]),
	([      "quest":                "衙役",
		"quest_type":           "杀",
		"where":                "官府",
		"diff":                 2,
	]),
	([      "quest":                "流氓头",
		"quest_type":           "杀",
		"where":                "街头",
		"diff":                 2,
	]),
	([      "quest":                "傣族首领",
		"quest_type":           "杀",
		"where":                "大理附近",
		"diff":                 2,
	]),
	([      "quest":                "韦春芳",
		"quest_type":           "杀",
		"where":                "丽春院",
		"diff":                 2,
	]),
	([      "quest":                "澡堂老板",
		"quest_type":           "杀",
		"where":                "桃源澡堂",
		"diff":                 2,
	]),
	([      "quest":                "裸体男人",
		"quest_type":           "杀",
		"where":                "桃源千金楼",
		"diff":                 2,
	]),
	([      "quest":                "裸体女人",
		"quest_type":           "杀",
		"where":                "桃源千金楼",
		"diff":                 2,
	]),
	([      "quest":                "彪形大汉",
		"quest_type":           "杀",
		"where":                "桃源千金楼",
		"diff":                 2,
	]),
	([      "quest":                "人贩子",
		"quest_type":           "杀",
		"where":                "桃源千金楼",
		"diff":                 2,
	]),
	([      "quest":                "凤天南",
		"quest_type":           "杀",
		"where":                "桃源戏楼",
		"diff":                 2,
	]),
	([      "quest":                "考官",
		"quest_type":           "杀",
		"where":                "桃源考场",
		"diff":                 2,
	]),

});
mapping query_quest()
{
	return quest[random(sizeof(quest))];
}
