// qlist100000.c

inherit SKILL;
#include <ansi.h>

mapping *quest = ({
        ([      "quest":                "桑三娘",
                "quest_type":           "杀",
                "where":                "黑木崖",
                "diff":                 1,
        ]),
        ([      "quest":                "仇松年",
                "quest_type":           "杀",
                "where":                "黑木崖",
                "diff":                 1,
        ]),
        ([      "quest":                "护法使者",
                "quest_type":           "杀",
                "where":                "黑木崖",
                "diff":                 1,
        ]),
        ([      "quest":                HIY"绣花小方巾"NOR,
                "quest_type":           "寻",
                "where":                "扬州成衣店",
                "diff":                 1,
        ]),
        ([      "quest":                HIY"黄袍"NOR,
                "quest_type":           "寻",
                "where":                "扬州成衣店",
                "diff":                 1,
        ]),
        ([      "quest":                RED"艳露凝香衣"NOR,
                "quest_type":           "寻",
                "where":                "扬州成衣店",
                "diff":                 1,
        ]),
        ([      "quest":                "五彩小战靴",
                "quest_type":           "寻",
                "where":                "桃源布庄",
                "diff":                 1,
        ]),
        ([      "quest":                "毡帽",
                "quest_type":           "寻",
                "where":                "桃源布庄",
                "diff":                 1,
        ]),
        ([      "quest":                "逍遥巾",
                "quest_type":           "寻",
                "where":                "桃源布庄",
                "diff":                 1,
        ]),
        ([      "quest":                HIW"雪白长裙"NOR,
                "quest_type":           "寻",
                "where":                "桃源布庄",
                "diff":                 1,
        ]),
        ([      "quest":                YEL"羊皮靴"NOR,
                "quest_type":           "寻",
                "where":                "桃源布庄",
                "diff":                 1,
        ]),
        ([      "quest":                "段无畏",
                "quest_type":           "杀",
                "where":                "大理镇南王府",
                "diff":                 1,
        ]),
        ([      "quest":                "江湖艺人",
                "quest_type":           "杀",
                "where":                "桃源城内",
                "diff":                 1,
        ]),
        ([      "quest":                "老祭司",
                "quest_type":           "杀",
                "where":                "大理的祭祀大屋",
                "diff":                 1,
        ]),
        ([      "quest":                "族长",
                "quest_type":           "杀",
                "where":                "大理附近的竹楼",
                "diff":                 1,
        ]),
        ([      "quest":                "华南虎",
                "quest_type":           "杀",
                "where":                "福州的闽赣古道",
                "diff":                 1,
        ]),
        ([      "quest":                "黑熊",
                "quest_type":           "杀",
                "where":                "关外的黑风口",
                "diff":                 1,
        ]),
        ([      "quest":                "完颜洪烈",
                "quest_type":           "杀",
                "where":                "苏州以北的青石官道",
                "diff":                 1,
        ]),
        ([      "quest":                "护法使者",
                "quest_type":           "杀",
                "where":                "黑木崖",
                "diff":                 1,
        ]),
        ([      "quest":                "石人武士",
                "quest_type":           "杀",
                "where":                "灵州赤陵",
                "diff":                 1,
        ]),
        ([      "quest":                "掌理道长",
                "quest_type":           "杀",
                "where":                "全真教大厅二进",
                "diff":                 1,
        ]),
        ([      "quest":                "火折",
                "quest_type":           "找",
                "where":                "苏州",
                "diff":                 1,
        ]),
        ([      "quest":                "阿拉伯弯刀",
                "quest_type":           "找",
                "where":                "星宿派附近",
                "diff":                 1,
        ]),
        ([      "quest":                "华山剑谱",
                "quest_type":           "找",
                "where":                "华山派",
                "diff":                 1,
        ]),
        ([      "quest":                "波斯长袍",
                "quest_type":           "找",
                "where":                "星宿派附近",
                "diff":                 1,
        ]),
        ([      "quest":                HIC"铁琵琶"NOR,
                "quest_type":           "找",
                "where":                "关外",
                "diff":                 1,
        ]),
        ([      "quest":                "维吾尔族长袍",
                "quest_type":           "找",
                "where":                "星宿派附近",
                "diff":                 1,
        ]),
        ([      "quest":                "辟邪剑谱",
                "quest_type":           "找",
                "where":                "华山派",
                "diff":                 1,
        ]),
        ([      "quest":                "束发金带",
                "quest_type":           "找",
                "where":                "桃花岛",
                "diff":                 1,
        ]),
        ([      "quest":                "大刀",
                "quest_type":           "找",
                "where":                "北京城",
                "diff":                 1,
        ]),
        ([      "quest":                "九节鞭",
                "quest_type":           "找",
                "where":                "归云庄",
                "diff":                 1,
        ]),
        ([      "quest":                "虎皮",
                "quest_type":           "找",
                "where":                "大理附近",
                "diff":                 1,
        ]),
        ([      "quest":                "锦缎",
                "quest_type":           "找",
                "where":                "北京城",
                "diff":                 1,
        ]),
        ([      "quest":                "三股叉",
                "quest_type":           "找",
                "where":                "黄河一带",
                "diff":                 1,
        ]),
});
mapping query_quest()
{
        return quest[random(sizeof(quest))];
}
