// qlist224000.c

inherit SKILL;
#include <ansi.h>

mapping *quest = ({
	([      "quest":                "李嫂",
		"quest_type":           "杀",
		"where":                "灵鹫宫",
		"diff":                 4,
	]),
	([      "quest":                "执事僧",
		"quest_type":           "杀",
		"where":                "少林寺",
		"diff":                 4,
	]),
	([      "quest":                "段誉",
		"quest_type":           "杀",
		"where":                "扬州城",
		"diff":                 4,
	]),
	([      "quest":                "常赫志",
		"quest_type":           "杀",
		"where":                "杭州天地会",
		"diff":                 4,
	]),
	([      "quest":                "常伯志",
		"quest_type":           "杀",
		"where":                "杭州天地会",
		"diff":                 4,
	]),
	([      "quest":                "仪和",
		"quest_type":           "杀",
		"where":                "恒山派",
		"diff":                 4,
	]),
	([      "quest":                "仪清",
		"quest_type":           "杀",
		"where":                "恒山派",
		"diff":                 4,
	]),
	([      "quest":                "仪质",
		"quest_type":           "杀",
		"where":                "恒山派",
		"diff":                 4,
	]),
	([      "quest":                "黄钟公",
		"quest_type":           "杀",
		"where":                "梅庄",
		"diff":                 4,
	]),
	([      "quest":                "卜沉",
		"quest_type":           "杀",
		"where":                "嵩山派",
		"diff":                 4,
	]),
	([      "quest":                "高克新",
		"quest_type":           "杀",
		"where":                "嵩山派",
		"diff":                 4,
	]),
	([      "quest":                "沙天江",
		"quest_type":           "杀",
		"where":                "嵩山派",
		"diff":                 4,
	]),
	([      "quest":                "黄蓉",
		"quest_type":           "杀",
		"where":                "桃花岛",
		"diff":                 4,
	]),
	([      "quest":                "刀师",
		"quest_type":           "杀",
		"where":                "血刀门",
		"diff":                 4,
	]),
	([      "quest":                "小侍童",
		"quest_type":           "杀",
		"where":                "桃花岛",
		"diff":                 4,
	]),
	([      "quest":                "小侍女",
		"quest_type":           "杀",
		"where":                "桃源城澡堂",
		"diff":                 4,
	]),
	([      "quest":                "霍青桐",
		"quest_type":           "杀",
		"where":                "杭州",
		"diff":                 4,
	]),
	([      "quest":                "鲁连荣",
		"quest_type":           "杀",
		"where":                "衡山",
		"diff":                 4,
	]),
	([      "quest":                "丁勉",
		"quest_type":           "杀",
		"where":                "嵩山派",
		"diff":                 4,
	]),
	([      "quest":                "费彬",
		"quest_type":           "杀",
		"where":                "嵩山派",
		"diff":                 4,
	]),
	([      "quest":                "乐厚",
		"quest_type":           "杀",
		"where":                "嵩山派",
		"diff":                 4,
	]),
	([      "quest":                "钟镇",
		"quest_type":           "杀",
		"where":                "嵩山派",
		"diff":                 4,
	]),
	([      "quest":                "建除道人",
		"quest_type":           "杀",
		"where":                "泰山派",
		"diff":                 4,
	]),
	([      "quest":                "天柏道人",
		"quest_type":           "杀",
		"where":                "泰山派",
		"diff":                 4,
	]),
	([      "quest":                "天松道人",
		"quest_type":           "杀",
		"where":                "泰山派",
		"diff":                 4,
	]),
	([      "quest":                "天乙道人",
		"quest_type":           "杀",
		"where":                "泰山派",
		"diff":                 4,
	]),
	([      "quest":                "李沅芷",
		"quest_type":           "杀",
		"where":                "苏堤",
		"diff":                 4,
	]),
	([      "quest":                "白振",
		"quest_type":           "杀",
		"where":                "苏州青石大道",
		"diff":                 4,
	]),
	([      "quest":                "文泰来",
		"quest_type":           "杀",
		"where":                "苏州青石大道",
		"diff":                 4,
	]),
});

mapping query_quest()
{
	return quest[random(sizeof(quest))];
}
