// qlist50000.c

inherit SKILL;
#include <ansi.h>
mapping *quest = ({
	([      "quest":                "闪躲入门",
		"quest_type":           "找",
		"where":		"桃源书屋",
		"diff":			1,
	]),
	([      "quest":                "闪躲进阶",
		"quest_type":           "找",
		"where":		"桃源书屋",
		"diff":			1,
	]),
	([      "quest":                "心法精要",
		"quest_type":           "找",
		"where":		"桃源书屋",
		"diff":			1,
	]),
	([      "quest":                "心法总诀",
		"quest_type":           "找",
		"where":		"桃源书屋",
		"diff":			1,
	]),
	([      "quest":                "掌法入门",
		"quest_type":           "找",
		"where":		"桃源书屋",
		"diff":			1,
	]),
	([      "quest":                "掌法进阶",
		"quest_type":           "找",
		"where":		"桃源书屋",
		"diff":			1,
	]),
	([      "quest":                "掌法精要",
		"quest_type":           "找",
		"where":		"桃源书屋",
		"diff":			1,
	]),
	([      "quest":                "掌法总诀",
		"quest_type":           "找",
		"where":		"桃源书屋",
		"diff":			1,
	]),
	([      "quest":                HIY"金创药"NOR,
		"quest_type":           "找",
		"where":		"药店",
		"diff":			1,
	]),
	([      "quest":                "木剑",
		"quest_type":           "找",
		"where":		"桃源兵器铺",
		"diff":			1,
	]),
	([      "quest":                "钢刀",
		"quest_type":           "找",
		"where":		"桃源兵器铺",
		"diff":			1,
	]),
	([      "quest":                "屠刀",
		"quest_type":           "找",
		"where":		"桃源兵器铺",
		"diff":			1,
	]),
	([      "quest":                "长枪",
		"quest_type":           "找",
		"where":		"桃源兵器铺",
		"diff":			1,
	]),
	([      "quest":                "鞭子",
		"quest_type":           "找",
		"where":		"桃源兵器铺",
		"diff":			1,
	]),
	([      "quest":                "千字文",
		"quest_type":           "找",
		"where":		"桃源书斋",
		"diff":			1,
	]),
	([      "quest":                "论语",
		"quest_type":           "找",
		"where":		"桃源书斋",
		"diff":			1,
	]),
	([      "quest":                "百家姓",
		"quest_type":           "找",
		"where":		"桃源书斋",
		"diff":			1,
	]),
	([      "quest":                "三字经",
		"quest_type":           "找",
		"where":		"书院",
		"diff":			1,
	]),
	([      "quest":                "面",
		"quest_type":           "找",
		"where":		"客栈",
		"diff":			1,
	]),
	([      "quest":                "葫芦",
		"quest_type":           "找",
		"where":		"苏州",
		"diff":			1,
	]),
});

mapping query_quest()
{
	return quest[random(sizeof(quest))];
}
