// qlist1200000.c

inherit SKILL;
#include <ansi.h>

mapping *quest = ({
	([      "quest":                "达而巴",
		"quest_type":           "杀",
		"where":		"雪山派",
		"diff":			6,
	]),
	([      "quest":                "嘉木活佛",
		"quest_type":           "杀",
		"where":		"雪山派",
		"diff":			6,
	]),
	([      "quest":                "拉章活佛",
		"quest_type":           "杀",
		"where":		"雪山派",
		"diff":			6,
	]),
	([      "quest":                "萨木活佛",
		"quest_type":           "杀",
		"where":		"雪山派",
		"diff":			6,
	]),
	([      "quest":                "善勇",
		"quest_type":           "杀",
		"where":		"血刀门",
		"diff":			6,
	]),
	([      "quest":                "狮吼子",
		"quest_type":           "杀",
		"where":		"星宿派",
		"diff":			6,
	]),
	([      "quest":                "莫声谷",
		"quest_type":           "杀",
		"where":		"武当派",
		"diff":			6,
	]),
	([      "quest":                "张翠山",
		"quest_type":           "杀",
		"where":		"武当派",
		"diff":			6,
	]),
	([      "quest":                "俞岱岩",
		"quest_type":           "杀",
		"where":		"武当派",
		"diff":			6,
	]),
	([      "quest":                HIC"「洛书」"NOR,
		"quest_type":           "拿",
		"where":		"桃花岛",
		"diff":			6,
	]),
	([      "quest":                "慧真尊者",
		"quest_type":           "杀",
		"where":		"少林寺",
		"diff":			6,
	]),
});
mapping query_quest()
{
	return quest[random(sizeof(quest))];
}
