// qlist50000.c

inherit SKILL;
#include <ansi.h>
mapping *quest = ({
	([      "quest":                "饺子",
		"quest_type":           "找",
		"where":		"桃源城的小贩",
		"diff":			1,
	]),
	([      "quest":                "包子",
		"quest_type":           "找",
		"where":		"客栈",
		"diff":			1,
	]),
	([      "quest":                HIG"玉花"NOR,
		"quest_type":           "找",
		"where":		"桃源珠宝店",
		"diff":			1,
	]),
	([      "quest":                "学生",
		"quest_type":           "杀",
		"where":		"桃源的圣贤书屋",
		"diff":			1,
	]),
	([      "quest":                "考生",
		"quest_type":           "杀",
		"where":		"桃源的考场",
		"diff":			1,
	]),
	([      "quest":                "穷汉",
		"quest_type":           "杀",
		"where":		"扬州城郊外",
		"diff":			1,
	]),
	([      "quest":                HIW"大石头"NOR,
		"quest_type":           "找",
		"where":		"扬州城郊外",
		"diff":			1,
	]),
	([      "quest":                "春红",
		"quest_type":           "杀",
		"where":		"桃源的千金楼",
		"diff":			1,
	]),
	([      "quest":                "夏红",
		"quest_type":           "杀",
		"where":		"桃源的千金楼",
		"diff":			1,
	]),
	([      "quest":                "妓女",
		"quest_type":           "杀",
		"where":		"桃源的千金楼",
		"diff":			1,
	]),
	([      "quest":                "丫环",
		"quest_type":           "杀",
		"where":		"桃源城",
		"diff":			1,
	]),
	([      "quest":                "秋红",
		"quest_type":           "杀",
		"where":		"桃源的千金楼",
		"diff":			1,
	]),
	([      "quest":                "年青公子",
		"quest_type":           "杀",
		"where":		"桃源的千金楼",
		"diff":			1,
	]),
	([      "quest":                "春菊",
		"quest_type":           "杀",
		"where":		"桃源的千金楼",
		"diff":			1,
	]),
	([      "quest":                "秋菊",
		"quest_type":           "杀",
		"where":		"桃源的千金楼",
		"diff":			1,
	]),
	([      "quest":                "冬菊",
		"quest_type":           "杀",
		"where":		"桃源的千金楼",
		"diff":			1,
	]),
	([      "quest":                "夏菊",
		"quest_type":           "杀",
		"where":		"桃源的千金楼",
		"diff":			1,
	]),
	([      "quest":                "冬红",
		"quest_type":           "杀",
		"where":		"桃源的千金楼",
		"diff":			1,
	]),
	([      "quest":                "鸨母",
		"quest_type":           "杀",
		"where":		"桃源的千金楼",
		"diff":			1,
	]),
});
mapping query_quest()
{
	return quest[random(sizeof(quest))];
}
