// qlist300000.c
#include <ansi.h>
inherit SKILL;

mapping *quest = ({
	([      "quest":                "木人",
		"quest_type":           "杀",
		"where":                "少林寺",
		"diff":                 3,
	]),
	([      "quest":                "武馆弟子",
		"quest_type":           "杀",
		"where":                "武馆",
		"diff":                 3,
	]),
	([      "quest":                "竹人",
		"quest_type":           "杀",
		"where":                "唐门",
		"diff":                 3,
	]),
	([      "quest":                "橡皮人",
		"quest_type":           "杀",
		"where":                "古墓派",
		"diff":                 3,
	]),
	([      "quest":                "机关人",
		"quest_type":           "杀",
		"where":                "桃花岛",
		"diff":                 3,
	]),
	([      "quest":                "史青山",
		"quest_type":           "杀",
		"where":                "扬州兵营",
		"diff":                 3,
	]),
	([      "quest":                "独臂神尼",
		"quest_type":           "杀",
		"where":                "北京客栈",
		"diff":                 3,
	]),
	([      "quest":                "木婉清",
		"quest_type":           "杀",
		"where":                "万劫谷",
		"diff":                 3,
	]),
	([      "quest":                "葛伦布",
		"quest_type":           "杀",
		"where":                "雪山寺山门",
		"diff":                 3,
	]),
	([      "quest":                "韩小莹",
		"quest_type":           "杀",
		"where":                "归云山庄",
		"diff":                 3,
	]),
	([      "quest":                "石双英",
		"quest_type":           "杀",
		"where":                "杭州",
		"diff":                 3,
	]),
	([      "quest":                "游讯",
		"quest_type":           "杀",
		"where":                "泉州城中心",
		"diff":                 3,
	]),
	([      "quest":                "李沅芷",
		"quest_type":           "杀",
		"where":                "杭州",
		"diff":                 3,
	]),
	([      "quest":                "段誉",
		"quest_type":           "杀",
		"where":                "扬州城内",
		"diff":                 3,
	]),
	([      "quest":                "扫地僧",
		"quest_type":           "杀",
		"where":                "少林寺",
		"diff":                 3,
	]),
	([      "quest":                "秦绢",
		"quest_type":           "杀",
		"where":                "恒山",
		"diff":                 3,
	]),
	([      "quest":                "郑萼",
		"quest_type":           "杀",
		"where":                "恒山",
		"diff":                 3,
	]),
	([      "quest":                "余婆婆",
		"quest_type":           "杀",
		"where":                "灵鹫宫",
		"diff":                 3,
	]),
	([      "quest":                "梁子翁",
		"quest_type":           "杀",
		"where":                "黄河一带",
		"diff":                 3,
	]),
	([      "quest":                "梅剑",
		"quest_type":           "杀",
		"where":                "灵鹫宫",
		"diff":                 3,
	]),
	([      "quest":                "乌鸦",
		"quest_type":           "杀",
		"where":                "武当山",
		"diff":                 3,
	]),
	([      "quest":                "彭连虎",
		"quest_type":           "杀",
		"where":                "苏州青石大道",
		"diff":                 3,
	]),
	([      "quest":                "沙通天",
		"quest_type":           "杀",
		"where":                "苏州青石大道",
		"diff":                 3,
	]),
	([      "quest":                "羊鞭",
		"quest_type":           "寻",
		"where":                "星宿海",
		"diff":                 3,
	]),
	([      "quest":                "狄修",
		"quest_type":           "杀",
		"where":                "嵩山附近",
		"diff":                 3,
	]),
	([      "quest":                "仪琳",
		"quest_type":           "杀",
		"where":                "恒山",
		"diff":                 3,
	]),
	([      "quest":                "衙役服",
		"quest_type":           "寻",
		"where":                "官府",
		"diff":                 3,
	]),
	([      "quest":                "游客",
		"quest_type":           "杀",
		"where":                "北京王府井街",
		"diff":                 3,
	]),
	([      "quest":                "摘星子",
		"quest_type":           "杀",
		"where":                "星宿海",
		"diff":                 3,
	]),
	([      "quest":                "高彦超",
		"quest_type":           "杀",
		"where":                "北京",
		"diff":                 3,
	]),
	([      "quest":                "史登达",
		"quest_type":           "杀",
		"where":                "嵩山附近",
		"diff":                 3,
	]),
});

mapping query_quest()
{
	return quest[random(sizeof(quest))];
}
