//questob.c

#include <ansi.h>

inherit F_SKILL;

mapping *quest=({
	(["quest":"雄黄(Xionghuang)",]),
	(["quest":"金叶(Gold leaf)",]),
	(["quest":"青陀螺花(Qingtuo luohua)",]),
	(["quest":"洋金花(Yang jinhua)",]),
	(["quest":"百草丹(Baicao dan)",]),
	(["quest":"蛇药(She yao)",]),
	(["quest":"金蛇胆(Jin)",]),
	(["quest":"青蛇胆(Qing)",]),
	(["quest":"蛇胆膏(Shedan gao)",]),
	(["quest":"断了的长剑(Duan jian)",]),
	(["quest":"蛇胆粉(Fen)",]),
	(["quest":"金蛇胆(Jin dan)",]),
	(["quest":"青蛇胆(Qing dan)",]),
	(["quest":"蛇胆膏(Shedan gao)",]),
	(["quest":"蛇肉(She rou)",]),
	(["quest":"明史辑略(Book ming)",]),
	(["quest":"四十二章经七(Book7)",]),
	(["quest":"四十二章经一(Book1)",]),
	(["quest":"四十二章经二(Book2)",]),
	(["quest":"四十二章经三(Book3)",]),
	(["quest":"四十二章经四(Book4)",]),
	(["quest":"四十二章经五(Book5)",]),
	(["quest":"四十二章经六(Book6)",]),
	(["quest":"四十二章经八(Book8)",]),
	(["quest":"纺纱机(Fangsha ji)",]),
	(["quest":"人参(Renshen)",]),
	(["quest":"蜂浆瓶(Fengjiangping)",]),
	(["quest":"黑木令(Heimu ling)",]),
	(["quest":"雪参玉蟾丹(Yuchan dan)",]),
	(["quest":"金冠蛇胆(Jin dan)",]),
	(["quest":"银冠蛇胆(Yin dan)",]),
	(["quest":"酸梅汤(Suanmei tang)",]),
	(["quest":"蟒蛇肉(Snake meat)",]),
	(["quest":"大白鱼(Fish)",]),
	(["quest":"少林英雄令(Yingxiong ling)",]),
	(["quest":"蟒蛇胆(Shedan)",]),
	(["quest":"施将军令牌(Shi lingpai)",]),
	(["quest":"百花腹蛇膏(Baihua gao)",]),
	(["quest":"无名花(Hua2)",]),
	(["quest":"腹蛇胆(Dan)",]),
	(["quest":"龙都香茗(Longdu xiang)",]),
	(["quest":"布阵箱(Buzhen xiang)",]),
	(["quest":"锦盒(Jin he)",]),
	(["quest":"香(Xiang)",]),
	(["quest":"女儿香(Nuer xiang)",]),
	(["quest":"腐心草(Fuxin cao)",]),
	(["quest":"腊八粥(Laba)",]),
	(["quest":"赏善铜牌(Shan pai)",]),
	(["quest":"罚恶铜牌(E pai)",]),
	(["quest":"清心散(Qingxin san)",]),
	(["quest":"铜钹(Tongbo)",]),
	(["quest":"铜鼓(Tonggu)",]),
	(["quest":"铜号(Tonghao)",]),
	(["quest":"三笑逍遥散(Sanxiaoxiaoyao san)",]),
	(["quest":"毒蛇胆(Shedan)",]),
	(["quest":"雪莲(Xue lian)",]),
	(["quest":HIW"世袭表"NOR"(Biao)",]),
	(["quest":HIW"玉玺"NOR"(Yu xi)",]),
	(["quest":HIW"纸卷"NOR"(Paper)",]),
	(["quest":GRN"碧蚕粉"NOR"(Bican feng)",]),
	(["quest":RED"鹤顶红"NOR"(Heding hong)",]),
	(["quest":BLU"孔雀胆"NOR"(Kongque dan)",]),
	(["quest":WHT"白术"NOR"(Bai shu)",]),
	(["quest":HIB"断血草"NOR"(Duan xuecao)",]),
	(["quest":HIG"甘草"NOR"(Gan cao)",]),
	(["quest":HIR"红花"NOR"(Hong hua)",]),
	(["quest":YEL"金钱草"NOR"(Jin qiancao)",]),
	(["quest":HIY"金银花"NOR"(Jinyin hua)",]),
	(["quest":MAG"蛇草"NOR"(She cao)",]),
	(["quest":HIG"越橘草"NOR"(Yue ju)",]),
	(["quest":RED"续命八丹"NOR"(Xuming badan)",]),
	(["quest":HIY"通犀地龙丸"NOR"(Dilong wan)",]),
	(["quest":HIY"金创药"NOR"(Jinchuang yao)",]),
	(["quest":HIY"田七鲨胆散"NOR"(Tianqi san)",]),
	(["quest":HIR"无常丹"NOR"(Wuchang dan)",]),
	(["quest":HIG"养精丹"NOR"(Yangjing dan)",]),
	(["quest":GRN"九花玉露丸"NOR"(Yulu wan)",]),
	(["quest":HIR"人参果"NOR"(Guo)",]),
	(["quest":HIC"玄冰碧火酒"NOR"(Xuanbingbihuo jiu)",]),
	(["quest":HIR"高粱米饭"NOR"(Rice)",]),
	(["quest":RED"樱桃火腿"NOR"(Yingtao huotui)",]),
	(["quest":WHT"菱白虾仁"NOR"(Lingbai xiaren)",]),
	(["quest":HIR"断肠花"NOR"(Hua3)",]),
	(["quest":HIC"翡翠兰"NOR"(Hua4)",]),
	(["quest":HIG"百香花"NOR"(Hua)",]),
	(["quest":HIR"熊胆"NOR"(Xiongdan)",]),
	(["quest":RED"血竭"NOR"(Xuejie)",]),
	(["quest":HIW"龟苓膏"NOR"(Guiling gao)",]),
	(["quest":HIB"乌龟甲"NOR"(Gui jia)",]),
	(["quest":WHT"何首乌"NOR"(Shouwu)",]),
	(["quest":GRN"人参果"NOR"(Renshen guo)",]),
	(["quest":HIR"山茶花"NOR"(Cha hua)",]),
	(["quest":YEL"黄米饭"NOR"(Rice)",]),
	(["quest":MAG"灵脂兰"NOR"(Lingzhi flower)",]),
	(["quest":HIR"朱果"NOR"(Zhu guo)",]),
	(["quest":RED"毒蝎壳"NOR"(Duxie ke)",]),
	(["quest":YEL"茯苓"NOR"(Fuling)",]),
	(["quest":HIW"没药"NOR"(Moyao)",]),
	(["quest":HIY"田七"NOR"(Tianqi)",]),
	(["quest":HIG"新鲜熊胆"NOR"(Dan)",]),
	(["quest":HIW"满月"NOR"(Cha hua)",]),
	(["quest":HIW"倚"HIG"栏"HIR"娇"NOR"(Cha hua)",]),
	(["quest":HIW"抓破"HIG"美"NOR"人"HIR"脸"NOR"(Cha hua)",]),
	(["quest":HIR"红妆"HIW"素裹"NOR"(Cha hua)",]),
	(["quest":HIB"眼"HIW"儿媚"NOR"(Cha hua)",]),
	(["quest":HIG"八宝妆"NOR"(Cha hua)",]),
	(["quest":HIR"二"WHT"乔"NOR"(Cha hua)",]),
	(["quest":MAG"风"WHT"尘三"HIR"侠"NOR"(Cha hua)",]),
	(["quest":HIR"七仙女"NOR"(Cha hua)",]),
	(["quest":HIB"八仙过海"NOR"(Cha hua)",]),
	(["quest":HIG"十三太保"NOR"(Cha hua)",]),
	(["quest":HIR"十八学士"NOR"(Cha hua)",]),
	(["quest":HIY"落第秀才"NOR"(Cha hua)",]),
	(["quest":"论语(Literateb4)",]),
	(["quest":"「河图」(Hetu)",]),
	(["quest":HIC"「洛书」"NOR"(Luoshu)",]),
	(["quest":"胡家刀谱残篇(Blade book)",]),
	(["quest":"帛卷(Bo juan)",]),
	(["quest":"易筋经文学篇(Shu)",]),
	(["quest":"意形步法(Bufa book)",]),
	(["quest":"碧血刀(Shu)",]),
	(["quest":"道德经「上卷」(Jing)",]),
	(["quest":"道德经(Shu)",]),
	(["quest":"『星宿毒经【下册】』(Du jing2)",]),
	(["quest":"太极十三势(Shu)",]),
	(["quest":"棋谱(Qi pu)",]),
	(["quest":"金雁图谱(Jinyan tu)",]),
	(["quest":"「九阳真经」第一卷(Jiuyang zhenjing1)",]),
	(["quest":"「九阳真经」第二卷(Jiuyang zhenjing2)",]),
	(["quest":"「九阳真经」第三卷(Jiuyang zhenjing3)",]),
	(["quest":"「九阳真经」第四卷(Jiuyang zhenjing4)",]),
	(["quest":"「九阴真经」上册(Jiuyin zhenjing1)",]),
	(["quest":"道德经「第一章」(Jing)",]),
	(["quest":"道德经「第十三章」(Jing)",]),
	(["quest":"道德经「第十六章」(Jing)",]),
	(["quest":"道德经「第十八章」(Jing)",]),
	(["quest":"道德经「第二章」(Jing)",]),
	(["quest":"道德经「第八章」(Jing)",]),
	(["quest":"三字经(Literateb1)",]),
	(["quest":"百家姓(Literateb2)",]),
	(["quest":"千字文(Literateb3)",]),
	(["quest":"六脉神剑谱(Pu)",]),
	(["quest":"大乘涅磐功(Mahayana book)",]),
	(["quest":"密宗心经(Jing)",]),
	(["quest":"大乘佛法一集(Buddhism book)",]),
	(["quest":"大乘佛法二集(Buddhism book2)",]),
	(["quest":"大乘佛法三集(Buddhism book3)",]),
	(["quest":"大乘佛法四集(Buddhism book4)",]),
	(["quest":"佛法真卷(Buddhism book5)",]),
	(["quest":"拳法总诀(Cuff book4)",]),
	(["quest":"闪躲总诀(Dodge book4)",]),
	(["quest":"指法总诀(Finger book4)",]),
	(["quest":"心法总诀(Force book4)",]),
	(["quest":"手法总诀(Hand book4)",]),
	(["quest":"招架总诀(Parry book4)",]),
	(["quest":"掌法总诀(Strike book4)",]),
	(["quest":"剑法总诀(Sword book4)",]),
	(["quest":"道家学说四集(Taoism book4)",]),
	(["quest":"道藏真卷(Taoism book5)",]),
	(["quest":"拳脚总诀(Unarmed book4)",]),
	(["quest":"辟邪剑谱(Pixie_sword_book)",]),
	(["quest":"天羽奇剑剑谱(Jian pu)",]),
	(["quest":"黄石谱(Huangshi pu)",]),
	(["quest":"七伤拳经(Qishang quanjing)",]),
	(["quest":"拳谱总诀(Shu)",]),
	(["quest":"群星璀璨图(Qunxing tu)",]),
	(["quest":"羊皮书(Skin)",]),
	(["quest":"杖法通解(Paper)",]),
	(["quest":"掌法总谱(Shu)",]),
	(["quest":"一阳指诀(Sunfinger book)",]),
	(["quest":"华山剑谱(Sword book)",]),
	(["quest":"天山器法(Throwing book)",]),
	(["quest":"风云手手法(Shaolin wuji)",]),
	(["quest":"一指禅功(Shaolin wuji)",]),
	(["quest":"韦陀棍法(Shaolin wuji)",]),
	(["quest":"「易经序卦篇」(Yijing xugua)",]),
	(["quest":"「易经说卦篇」(Yijing shuogua)",]),
	(["quest":"「易经杂卦篇」(Yijing zagua)",]),
	(["quest":"「易经系辞篇」(Yijing xici)",]),
	(["quest":"易筋经(Yijinjing)",]),
	(["quest":"云龙鞭法(Bian book)",]),
	(["quest":"云龙剑谱(Jian book)",]),
	(["quest":"云龙经(Shu)",]),
	(["quest":"云龙经「上卷」(Jing)",]),
	(["quest":"云龙经「下卷」(Jing)",]),
	(["quest":"玉女剑谱(Yunu book)",]),
	(["quest":"玉女心经上册(Jing1)",]),
	(["quest":"玉女心经下册(Jing2)",]),
	(["quest":"昊天掌法谱(Zhangfa pu)",]),
	(["quest":"正气吟(Zhengqi_book)",]),
	(["quest":"一阳指法谱(Zhifa pu)",]),
	(["quest":"周天图(Shu)",]),
	(["quest":"紫霞密芨(Zixia_book)",]),
	(["quest":"拳谱总诀(Shu)",]),
	(["quest":"云龙经(Shu)",]),
	(["quest":"葵花宝典(Kuihua baodian)",]),
	(["quest":"吸星大法(Xixing-force book)",]),
	(["quest":"天羽奇剑剑谱(Jian pu)",]),
	(["quest":"群星璀璨图(Qunxing tu)",]),
	(["quest":YEL"洗髓经"NOR"(Xisuijing)",]),
	(["quest":"「九阴真经」下册(Jiuyin zhenjing2)",]),
	(["quest":"道德经「第十三章」(Jing)",]),
	(["quest":"羊皮书(Skin)",]),
	(["quest":"匕首(Dagger)",]),
	(["quest":"精钢剑(Long sword)",]),
	(["quest":HIR"匕首"NOR"(Bishou)",]),
	(["quest":HIB"铁笛"NOR"(Tie di)",]),
	(["quest":"软剑(Ruanjian)",]),
	(["quest":HIC"玄铁重剑"NOR"(Xuantie jian)",]),
	(["quest":HIC"君子剑"NOR"(Junzijian)",]),
	(["quest":HIM"淑女剑"NOR"(Shunvjian)",]),
	(["quest":HIC"短剑"NOR"(Short sword)",]),
	(["quest":HIG"凝碧剑"NOR"(Green_water_sword)",]),
	(["quest":"判官笔(Panguan bi)",]),
	(["quest":"玉箫(Yu xiao)",]),
	(["quest":HIG"碧水剑"NOR"(Green_water_sword)",]),
	(["quest":CYN"龙泉剑"NOR"(Longquan sword)",]),
	(["quest":YEL"金蛇剑"NOR"(Jinshe jian)",]),
	(["quest":HIW"白玉瑶琴"NOR"(Yao qin)",]),
	(["quest":"南海神木(Sea wood)",]),
	(["quest":"圣火令(Shenghuo ling)",]),
	(["quest":"倚天剑(Yitian jian)",]),
	(["quest":"桃木剑(Taomu jian)",]),
	(["quest":"游龙剑(Youlong sword)",]),
	(["quest":"细铁杆(Tie-gan)",]),
	(["quest":HIW"白虹剑"NOR"(Baihongjian)",]),
	(["quest":"碧玉剑(Biyu jian)",]),
	(["quest":HIG"碧玉剑"NOR"(Biyu jian)",]),
	(["quest":"钢刀(Gang dao)",]),
	(["quest":"屠刀(Knife)",]),
	(["quest":HIM"屠龙刀"NOR"(Tulong dao)",]),
	(["quest":"大刀(Da dao)",]),
	(["quest":"柴刀(Cai dao)",]),
	(["quest":"戒刀(Jie dao)",]),
	(["quest":"砍刀(Kan dao)",]),
	(["quest":"蛮刀(Man dao)",]),
	(["quest":"菜刀(Cai dao)",]),
	(["quest":"闯王宝刀(Chuangwang baodao)",]),
	(["quest":"尖刀(Jian dao)",]),
	(["quest":CYN"柳叶刀"NOR"(Liuye dao)",]),
	(["quest":"短刀(Duan dao)",]),
	(["quest":"武士刀(Wushi dao)",]),
	(["quest":"阿拉伯弯刀(Wandao)",]),
	(["quest":HIW"八卦刀"NOR"(Bagua dao)",]),
	(["quest":HIM"紫金"HIY"八卦刀"NOR"(Zijin baguadao)",]),
	(["quest":"木镗(Mu tang)",]),
	(["quest":"伏魔刀(Fumo dao)",]),
	(["quest":"铁焰令(Tieyan ling)",]),
	(["quest":"倭刀(Wo dao)",]),
	(["quest":HIR"血刀"NOR"(Blood blade)",]),
	(["quest":HIR"赤血刀"NOR"(Chi blade)",]),
});

mapping query_quest()
{
	return quest[random(sizeof(quest))];
}
